# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17dN_oxXpwTGM9tEyoM7jMKHrgW1g3IYi
"""

pip install openai pandas streamlit langchain faiss-cpu

from openai import OpenAI

client = OpenAI(api_key="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")

import pandas as pd

def analyze_balance_sheet(file):
    df = pd.read_excel(file)

    summary = {}

    summary["Total Income"] = df["Income"].sum()
    summary["Total Expenses"] = df["Expenses"].sum()
    summary["Profit"] = summary["Total Income"] - summary["Total Expenses"]

    if summary["Profit"] > 0:
        summary["Status"] = "Profit"
    else:
        summary["Status"] = "Loss"

    return summary

from openai import OpenAI

client = OpenAI(api_key="your_api_key")

def ask_agent(user_query, data_summary):
    prompt = f"""
    You are an income tax assistant.
    Analyze this data: {data_summary}
    Answer this: {user_query}
    """

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}]
    )

    return response.choices[0].message.content

import streamlit as st
import pandas as pd
from openai import OpenAI

# Initialize OpenAI client (from eQXnBpWNnFQJ)
client = OpenAI(api_key="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")

# Define analyze_balance_sheet function (from x3aewjSqn7Bo)
def analyze_balance_sheet(file):
    df = pd.read_excel(file)

    summary = {}

    summary["Total Income"] = df["Income"].sum()
    summary["Total Expenses"] = df["Expenses"].sum()
    summary["Profit"] = summary["Total Income"] - summary["Total Expenses"]

    if summary["Profit"] > 0:
        summary["Status"] = "Profit"
    else:
        summary["Status"] = "Loss"

    return summary

# Define ask_agent function (from OCehk3hOoB-5, using the correct client)
def ask_agent(user_query, data_summary):
    prompt = f"""
    You are an income tax assistant.
    Analyze this data: {data_summary}
    Answer this: {user_query}
    """

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}]
    )

    return response.choices[0].message.content

st.title("Tax Assistant Agent")

file = st.file_uploader("Upload Balance Sheet", type=["xlsx"])

if file:
    summary = analyze_balance_sheet(file)
    st.write("Summary:", summary)

    query = st.text_input("Ask something about this data")

    if query:
        answer = ask_agent(query, summary)
        st.write("Agent:", answer)

with open('app.py', 'w') as f:
    f.write('''import streamlit as st
import pandas as pd
from openai import OpenAI

# Initialize OpenAI client (from eQXnBpWNnFQJ)
client = OpenAI(api_key="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")

# Define analyze_balance_sheet function (from x3aewjSqn7Bo)
def analyze_balance_sheet(file):
    df = pd.read_excel(file)

    summary = {}

    summary["Total Income"] = df["Income"].sum()
    summary["Total Expenses"] = df["Expenses"].sum()
    summary["Profit"] = summary["Total Income"] - summary["Total Expenses"]

    if summary["Profit"] > 0:
        summary["Status"] = "Profit"
    else:
        summary["Status"] = "Loss"

    return summary

# Define ask_agent function (from OCehk3hOoB-5, using the correct client)
def ask_agent(user_query, data_summary):
    prompt = f"""
    You are an income tax assistant.
    Analyze this data: {data_summary}
    Answer this: {user_query}
    """

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}]
    )

    return response.choices[0].message.content

st.title("Tax Assistant Agent")

file = st.file_uploader("Upload Balance Sheet", type=["xlsx"])

if file:
    summary = analyze_balance_sheet(file)
    st.write("Summary:", summary)

    query = st.text_input("Ask something about this data")

    if query:
        answer = ask_agent(query, summary)
        st.write("Agent:", answer)
''')

!streamlit run app.py

!pip install streamlit pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# st.title("My Tax Agent")
# st.write("App is running successfully 🚀")

!streamlit run app.py &>/content/logs.txt &

from pyngrok import ngrok

# Replace "YOUR_AUTH_TOKEN" with your actual ngrok authentication token
ngrok.set_auth_token("3Bbz3ZVKXp6rMD5QGX8ct3EG816_6oYHzmktSqdWX5k2APFPg")

public_url = ngrok.connect(8501)
public_url

import streamlit as st
import pandas as pd
from openai import OpenAI

client = OpenAI(api_key="YOUR_API_KEY")

st.title("💼 AI Tax Assistant")

# Store chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

# File upload
file = st.file_uploader("Upload Balance Sheet", type=["xlsx"])

if file:
    df = pd.read_excel(file)
    st.success("File uploaded successfully ✅")

# Display chat history
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.write(msg["content"])

# Chat input
user_input = st.chat_input("Ask something about your data...")

if user_input:
    st.session_state.messages.append({"role": "user", "content": user_input})

    with st.chat_message("user"):
        st.write(user_input)

    if file:
        prompt = f"Data:\n{df.to_string()}\n\nQuestion: {user_input}"
    else:
        prompt = user_input

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}]
    )

    answer = response.choices[0].message.content

    st.session_state.messages.append({"role": "assistant", "content": answer})

    with st.chat_message("assistant"):
        st.write(answer)

system_prompt = """
You are an expert Indian tax assistant.
- Analyze financial data
- Suggest tax saving options
- Highlight anomalies
- Be professional and concise
"""

if file:
    st.write("### 📊 Auto Insights")

    st.write("Total Income:", df["Income"].sum())
    st.write("Total Expenses:", df["Expenses"].sum())